#!/bin/sh

if [ $# -ne 1 ]
then
  echo "mk-ud-supp: usage: data" 1>&2
  exit 111
fi

IFS="
"

cat <<EOF
(table supported
  (t-row
    (item supported_header "System")
    (item supported_header "System Version")
    (item supported_header "Architecture")
    (item supported_header "CC Name")
    (item supported_header "CC Version")
    (item supported_header "Ada")
    (item supported_header "Ada Version"))
EOF

for line in `sort < "$1"`
do
  sys=`echo $line | awk '{print $1}'`
  ver=`echo $line | awk '{print $2}'`
  ccn=`echo $line | awk '{print $3}'`
  ccv=`echo $line | awk '{print $4}'`
  arc=`echo $line | awk '{print $5}'`
  aan=`echo $line | awk '{print $6}'`
  aav=`echo $line | awk '{print $7}'`

  if [ -z "${arc}" ]; then arc="n/a"; fi
  if [ -z "${aan}" ]; then aan="n/a"; fi
  if [ -z "${aav}" ]; then aav="n/a"; fi

  cat <<EOF
  (t-row
    (item "${sys}")
    (item "${ver}")
    (item "${arc}")
    (item "${ccn}")
    (item "${ccv}")
    (item "${aan}")
    (item "${aav}"))
EOF
done

cat <<EOF
)
EOF
